send data periodically
codex-team/devops-monitor pull request #5
Opened 2019-10-29 17:24 UTC by f0m41h4u7

launch with: ./begin.sh -t 60 -a http://example.com/monitor/v1/server-data?server-name=abc.com

2019-11-06 08:26 UTC, n0str approved these changes

2019-11-07 15:00 UTC, kabachook requested changes

2019-11-07 15:00 UTC, kabachook commented on mon.sh
> +server_address=$1
Add ip address validation

2019-11-18 05:21 UTC, kabachook approved these changes

2019-11-18 05:38 UTC, merged